# Generated by Django 4.0.5 on 2022-09-28 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_lesson_course_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images')),
                ('number_of_lesson', models.IntegerField()),
                ('average_time', models.CharField(max_length=150)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
            options={
                'ordering': ('-course_name',),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE, to='app2.course'),
        ),
    ]
